import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const lib = require("../lib.js");

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LESS_DIR = path.join(__dirname, "less");

// Absolute paths to each fixture file
const VARS   = path.join(LESS_DIR, "variables.less");
const MIXINS = path.join(LESS_DIR, "mixins.less");
const MAIN   = path.join(LESS_DIR, "main.less");
const BUTTON = path.join(LESS_DIR, "components", "button.less");
const CARD   = path.join(LESS_DIR, "components", "card.less");

// Remove all .css files generated by compileLess during tests
function cleanCSS(dir = LESS_DIR)
{
	for (const f of fs.readdirSync(dir))
	{
		const full = path.join(dir, f);
		if (fs.statSync(full).isDirectory()) cleanCSS(full);
		else if (f.endsWith(".css")) fs.unlinkSync(full);
	}
}

// ─── parseDependencies ───────────────────────────────────────────────────────

describe("parseDependencies", () =>
{
	let deps;
	beforeEach(() => { deps = {}; });

	it("adds nothing for a file with no imports", () =>
	{
		lib.parseDependencies(VARS, deps);
		expect(deps).toEqual({});
	});

	it("maps a single @import to the importing file", () =>
	{
		lib.parseDependencies(MIXINS, deps);
		expect(deps[VARS]).toContain(MIXINS);
	});

	it("maps multiple @imports from the same file", () =>
	{
		lib.parseDependencies(MAIN, deps);
		expect(deps[VARS]).toContain(MAIN);
		expect(deps[MIXINS]).toContain(MAIN);
	});

	it("infers .less extension when @import omits it", () =>
	{
		// mixins.less uses @import 'variables' (no .less)
		lib.parseDependencies(MIXINS, deps);
		expect(Object.keys(deps)).toContain(VARS);
	});

	it("resolves @import paths relative to the importing file", () =>
	{
		// button.less uses @import '../variables' — resolved relative to components/
		lib.parseDependencies(BUTTON, deps);
		expect(deps[VARS]).toContain(BUTTON);
		expect(deps[MIXINS]).toContain(BUTTON);
	});

	it("does not add duplicate entries when called twice", () =>
	{
		lib.parseDependencies(MIXINS, deps);
		lib.parseDependencies(MIXINS, deps);
		expect(deps[VARS]).toHaveLength(1);
	});
});

// ─── directoryCrawler ────────────────────────────────────────────────────────

describe("directoryCrawler", () =>
{
	it("finds all five fixture .less files", () =>
	{
		const found = [];
		lib.directoryCrawler(LESS_DIR, f => found.push(f));
		expect(found).toHaveLength(5);
	});

	it("includes root-level .less files", () =>
	{
		const found = [];
		lib.directoryCrawler(LESS_DIR, f => found.push(f));
		expect(found).toContain(VARS);
		expect(found).toContain(MIXINS);
		expect(found).toContain(MAIN);
	});

	it("recursively includes .less files in subdirectories", () =>
	{
		const found = [];
		lib.directoryCrawler(LESS_DIR, f => found.push(f));
		expect(found).toContain(BUTTON);
		expect(found).toContain(CARD);
	});

	it("does not include non-.less files", () =>
	{
		const found = [];
		lib.directoryCrawler(LESS_DIR, f => found.push(f));
		expect(found.every(f => f.endsWith(".less"))).toBe(true);
	});
});

// ─── initDependencies ────────────────────────────────────────────────────────

describe("initDependencies", () =>
{
	it("populates the full dependency map for the fixture directory", () =>
	{
		const deps = {};
		lib.initDependencies(LESS_DIR, deps);

		// variables.less is imported by all four other files
		expect(deps[VARS]).toContain(MIXINS);
		expect(deps[VARS]).toContain(MAIN);
		expect(deps[VARS]).toContain(BUTTON);
		expect(deps[VARS]).toContain(CARD);

		// mixins.less is imported by main and button
		expect(deps[MIXINS]).toContain(MAIN);
		expect(deps[MIXINS]).toContain(BUTTON);
	});

	it("does not create an entry for files that are never imported", () =>
	{
		const deps = {};
		lib.initDependencies(LESS_DIR, deps);
		// main, button, card are never @import-ed by anything
		expect(deps[MAIN]).toBeUndefined();
		expect(deps[BUTTON]).toBeUndefined();
		expect(deps[CARD]).toBeUndefined();
	});
});

// ─── compileLess ─────────────────────────────────────────────────────────────

describe("compileLess", () =>
{
	afterEach(() => cleanCSS());

	it("calls onStart with the file path before compiling", () =>
		new Promise((resolve, reject) =>
		{
			const onStart = vi.fn();
			lib.compileLess(VARS, {
				onStart,
				onSuccess: () => { expect(onStart).toHaveBeenCalledWith(VARS); resolve(); },
				onError: reject,
			});
		})
	);

	it("writes the compiled CSS file to disk", () =>
		new Promise((resolve, reject) =>
		{
			const outFile = VARS.replace(/\.less$/, ".css");
			lib.compileLess(VARS, {
				onSuccess: () =>
				{
					expect(fs.existsSync(outFile)).toBe(true);
					resolve();
				},
				onError: reject,
			});
		})
	);

	it("compiled CSS contains resolved variable values from @imports", () =>
		new Promise((resolve, reject) =>
		{
			// main.less imports variables and uses @primary-color in CSS rules
			const outFile = MAIN.replace(/\.less$/, ".css");
			lib.compileLess(MAIN, {
				onSuccess: () =>
				{
					const css = fs.readFileSync(outFile, "utf8");
					expect(css).toContain("#333333"); // @primary-color resolved
					resolve();
				},
				onError: reject,
			});
		})
	);

	it("calls onSuccess with the output file path", () =>
		new Promise((resolve, reject) =>
		{
			const outFile = VARS.replace(/\.less$/, ".css");
			lib.compileLess(VARS, {
				onSuccess: (out) => { expect(out).toBe(outFile); resolve(); },
				onError: reject,
			});
		})
	);

	it("compiles a file that uses @import (resolves imports)", () =>
		new Promise((resolve, reject) =>
		{
			lib.compileLess(MAIN, {
				onSuccess: () =>
				{
					const css = fs.readFileSync(MAIN.replace(/\.less$/, ".css"), "utf8");
					expect(css).toContain("#333333"); // @primary-color resolved
					resolve();
				},
				onError: reject,
			});
		})
	);

	it("calls onError for invalid LESS syntax", () =>
		new Promise((resolve) =>
		{
			const badFile = path.join(LESS_DIR, "_bad_syntax.less");
			fs.writeFileSync(badFile, ".broken { .nonexistent-mixin-xyz(); }");
			lib.compileLess(badFile, {
				onSuccess: () => { fs.unlinkSync(badFile); resolve(); },
				onError: (e) =>
				{
					expect(e).toBeTruthy();
					fs.unlinkSync(badFile);
					resolve();
				},
			});
		})
	);

	it("calls onError when the file does not exist", () =>
		new Promise((resolve) =>
		{
			lib.compileLess(path.join(LESS_DIR, "nonexistent.less"), {
				onSuccess: () => resolve(), // shouldn't happen
				onError: (e) => { expect(e).toBeTruthy(); resolve(); },
			});
		})
	);
});

// ─── compileWithDependents ───────────────────────────────────────────────────

describe("compileWithDependents", () =>
{
	it("compiles only the target file when it has no dependents", () =>
	{
		const compileFn = vi.fn();
		lib.compileWithDependents(MAIN, {}, compileFn);
		expect(compileFn).toHaveBeenCalledOnce();
		expect(compileFn).toHaveBeenCalledWith(MAIN);
	});

	it("compiles the target file and all transitive dependents", () =>
	{
		const compileFn = vi.fn();
		const deps = {};
		lib.initDependencies(LESS_DIR, deps);

		// variables is imported by all four others
		lib.compileWithDependents(VARS, deps, compileFn);

		expect(compileFn).toHaveBeenCalledWith(VARS);
		expect(compileFn).toHaveBeenCalledWith(MIXINS);
		expect(compileFn).toHaveBeenCalledWith(MAIN);
		expect(compileFn).toHaveBeenCalledWith(BUTTON);
		expect(compileFn).toHaveBeenCalledWith(CARD);
		expect(compileFn).toHaveBeenCalledTimes(5);
	});

	it("compiles only direct and transitive dependents of mixins (not variables or card)", () =>
	{
		const compileFn = vi.fn();
		const deps = {};
		lib.initDependencies(LESS_DIR, deps);

		lib.compileWithDependents(MIXINS, deps, compileFn);

		expect(compileFn).toHaveBeenCalledWith(MIXINS);
		expect(compileFn).toHaveBeenCalledWith(MAIN);
		expect(compileFn).toHaveBeenCalledWith(BUTTON);
		expect(compileFn).not.toHaveBeenCalledWith(VARS);
		expect(compileFn).not.toHaveBeenCalledWith(CARD);
		expect(compileFn).toHaveBeenCalledTimes(3);
	});

	it("does not compile the same file twice even if reached via multiple paths", () =>
	{
		const compileFn = vi.fn();
		const deps = {};
		lib.initDependencies(LESS_DIR, deps);

		// main.less imports both variables and mixins, so it could be reached
		// via two paths when variables is changed. It should only compile once.
		lib.compileWithDependents(VARS, deps, compileFn);

		const mainCalls = compileFn.mock.calls.filter(([f]) => f === MAIN);
		expect(mainCalls).toHaveLength(1);
	});

	it("handles circular imports without throwing or looping infinitely", () =>
	{
		const compileFn = vi.fn();
		const circular = { [VARS]: [MIXINS], [MIXINS]: [VARS] };

		expect(() => lib.compileWithDependents(VARS, circular, compileFn)).not.toThrow();
		expect(compileFn).toHaveBeenCalledTimes(2);
	});
});
